### ISSUE TITLE
Request adding a new "horizontal bar" icon

### ISSUE THREAD

**Issue by c933103** [ijprest/keyboard-layout-editor#233] opened 2018-09-11 11:03 UTC
I would like to add a horizontal bar to bottom part of one of the key on a layout I want to create to indicate that there should be an indicator light on the key in the shape of horizontal bar. Please add the icon into the tool.

**Comment by ijprest** [comment] 2018-09-12 01:08
Duplicate of #12 (support for windowed keycaps).

**Closed by ijprest** 2018-09-12 01:08 UTC
