### ISSUE TITLE
firefox permalink issue

### ISSUE THREAD

**Issue by bemace** [ijprest/keyboard-layout-editor#66] opened 2014-10-05 19:51 UTC
This one didn't work for me in Firefox. Fine in Chrome.

http://www.keyboard-layout-editor.com/##@@_y:0.25&p=DSA&a:7;&=F1&=F2&=F3&=F4&_x:7&c=#808080&a:4;&=Num%20Lock&=//&=*&=-;&@_c=#cccccc&a:7;&=F5&=F6&=F7&=F8&_x:2.5&a:4;&=Insert&=Home&=PgUp&_x:1.5&a:5;&=7%0AHome&=8%0A%E2%86%91&=9%0APgUp&_c=#808080&a:4&h:2;&=+;&@_c=#cccccc&a:7;&=F9&=F10&=F11&=F12&_x:2.5&a:4;&=Delete&=End&=PgDn&_x:1.5&a:5;&=4%0A%E2%86%90&=5&=6%0A%E2%86%92;&@_x:7.5&a:7;&=%E2%86%91&_x:2.5&a:5;&=1%0AEnd&=2%0A%E2%86%93&=3%0APgDn&_c=#808080&a:4&h:2;&=Enter;&@_c=#ff0000&a:7;&=Esc&_x:0.25&c=#cccccc;&=PrtSc&=Scroll%20Lock&=Pause%0ABreak&_x:2.25;&=%E2%86%90&=%E2%86%93&=%E2%86%92&_x:1.5&a:5&w:2;&=0%0AIns&=.%0ADel;&@_y:0.5;&=~%0A%60&=!%0A1&=/@%0A2&=#%0A3&=$%0A4&=%25%0A5&=%5E%0A6&=/&%0A7&=*%0A8&=(%0A9&=)%0A0&=/_%0A-&=+%0A/=&_c=#808080&w:2;&=Backspace;&@_a:4&w:1.5;&=Tab&_c=#cccccc&a:7;&=Q&=W&=E&=R&=T&=Y&=U&=I&=O&=P&_a:4;&=%7B%0A%5B&=%7D%0A%5D&_w:1.5;&=%7C%0A%5C;&@_c=#808080&w:1.75;&=Caps%20Lock&_c=#cccccc&a:7;&=A&=S&=D&=F&=G&=H&=J&=K&=L&_a:4;&=/:%0A/;&=%22%0A%27&_c=#808080&w:2.25;&=Enter;&@_w:2.25;&=Shift&_c=#cccccc&a:7;&=Z&=X&=C&=V&=B&=N&=M&_a:4;&=%3C%0A,&=%3E%0A.&=?%0A//&_c=#808080&w:2.75;&=Shift;&@_w:1.25;&=Ctrl&_w:1.25;&=Win&_w:1.25;&=Alt&_c=#cccccc&w:6.25;&=&_c=#808080&w:1.25;&=Alt&_w:1.25;&=Win&_w:1.25;&=Menu&_w:1.25;&=Ctrl

**Comment by kamilnine** [comment] 2015-02-24 23:09
Another one:

http://www.keyboard-layout-editor.com/##@@_x:2%3B&=%23%0A3%0AF3&_x:10.5%3B&=*%0A8%0AF8%3B&@_y:-0.875&x:1%3B&=%2F@%0A2%0AF2&_x:1%3B&=$%0A4%0AF4&_x:8.5%3B&=%2F&%0A7%0AF7&_x:1%3B&=(%0A9%0AF9%3B&@_y:-0.875&x:4%3B&=%25%0A5%0AF5&_x:6.5%3B&=%5E%0A6%0AF6%3B&@_y:-0.875%3B&=!%0A1%0AF1&_x:14.5%3B&=)%0A0%0AF10%3B&@_y:-0.375&x:2%3B&=E&_x:10.5%3B&=I%3B&@_y:-0.875&x:1%3B&=W&_x:1%3B&=R&_x:8.5%3B&=U&_x:1%3B&=O%0A%0AF11%3B&@_y:-0.875&x:4%3B&=T&_h:1.5%3B&=Space&_x:4.5&h:1.5%3B&=Back%20Space&=Y%3B&@_y:-0.875%3B&=Q&_x:14.5%3B&=P%0A%0AF12%3B&@_y:-0.375&x:2%3B&=D&_x:10.5%3B&=K%3B&@_y:-0.875&x:1%3B&=S&_x:1%3B&=F&_x:8.5%3B&=J&_x:1%3B&=L%3B&@_y:-0.875&x:4%3B&=G&_x:6.5%3B&=H%3B&@_y:-0.875%3B&=A&_x:14.5%3B&=%2F:%0A%2F%3B%3B&@_y:-0.625&x:5&h:1.5%3B&=Tab&_x:4.5&h:1.5%3B&=Enter%3B&@_y:-0.75&x:2%3B&=C&_x:10.5%3B&=%3C%0A,%3B&@_y:-0.875&x:1%3B&=X&_x:1%3B&=V&_x:8.5%3B&=M&_x:1%3B&=%3E%0A.%3B&@_y:-0.875&x:4%3B&=B&_x:6.5%3B&=N%3B&@_y:-0.875%3B&=Z&_x:14.5%3B&=%3F%0A%2F%2F%3B&@_r:30&rx:5&ry:4.25&h:2%3B&=Shift&_h:2%3B&=Ctrl&=Esc%3B&@_x:2%3B&=Mod%3B&@_r:-30&rx:11.5&x:-3%3B&=w00t&_h:2%3B&=Alt&_h:2%3B&=Alt%20Gr%3B&@_x:-3%3B&=Fn

**Comment by ijprest** [comment] 2015-07-07 01:26
I can see the problem in Firefox-39, but both links are working for me in a bleeding-edge version (41a)... and they work in both Chrome (43) & IE (10).

I dug around on Bugzilla for a bit, and found [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1093611#c56), which I think is the cause (and which was fixed in v41).  So I don't think there's anything to do on my side.

**Closed by ijprest** 2015-07-07 01:26 UTC
Labels: bug
