### ISSUE TITLE
Would be amazing if the raw data area could highlight the key you have currently selected, or even just its row of data

### ISSUE THREAD

**Issue by dragon788** [ijprest/keyboard-layout-editor#153] opened 2015-11-29 20:01 UTC
I'm a strings kind of guy, I don't mind a GUI editor for getting the structure in place, but when screen real estate is an issue I prefer to have the layout and the data and don't need much else.

**Comment by ijprest** [comment] 2018-09-14 06:26
Duplicate of #23.

**Closed by ijprest** 2018-09-14 06:26 UTC
Labels: duplicate
