### ISSUE TITLE
Use saved layout as preset

### ISSUE THREAD

**Issue by lindhe** [ijprest/keyboard-layout-editor#173] opened 2016-07-25 17:47 UTC
It would be useful to be able to create a new layout based on an existing layout previously created (not just the default presets).

**Comment by iandoug** [comment] 2016-09-05 05:25
1. Export the layout you have created (on the Raw Data tab, use the Download JSON button).
2. When you want to reuse that layout, use the Upload JSON button which is next to it.
Otherwise use the "Save" button (which requires you to have a Github account, data is saved there) and keep a copy of the URL that it generates.

I would agree that steps 1 and 2 above could be more 'obvious', it is a little hidden. That's probably a by-product of doing what is effectively a desktop app as a single web page. No "File" menu item... :-)

**Comment by lindhe** [comment] 2016-09-05 18:58
Yeah, I figured that out eventually. But I still think a one-click-button would be useful.

**Comment by ijprest** [comment] 2018-09-14 06:42
Duplicate of #108.

**Closed by ijprest** 2018-09-14 06:42 UTC
Labels: duplicate
