### ISSUE TITLE
Editing a single text field on a group of keys wipes out the other text fields

### ISSUE THREAD

**Issue by D1SC0tech** [ijprest/keyboard-layout-editor#86] opened 2015-07-07 12:18 UTC
Steps to reproduce:
- Open the ANSI-104 preset
- Click on the `/~ key, hold shift, and click on the =/+ key (selects all the keys in-between)
- Click on the Top Label field in Properties and delete the +
- The Bottom Label of all the keys will be changed to =

Expected behavior:
- The Top Label of all keys should be deleted while the Bottom Label should remain unaffected

This most likely happens because all of a key's text fields are stored in one value.

**Comment by ijprest** [comment] 2015-07-08 00:16
Confirmed... and yeah, that's the reason.  I had to do something about that to fix #63 sensibly anyway, so maybe I'll do it sooner rather than later.

**Comment by ijprest** [comment] 2015-07-31 21:04
Fixed in 09a4e62607d9a08a7349eaa4b6c3eaf56086a9e5.

**Closed by ijprest** 2015-07-31 21:04 UTC
Labels: bug
