### ISSUE TITLE
Key groups for styling purposes.

### ISSUE THREAD

**Issue by guest20** [ijprest/keyboard-layout-editor#155] opened 2016-02-06 22:42 UTC
It would be really nice if I could easily tag keys so that I can style them within the UI.

This would make it much easier to change colours on a board, especially considering how troublesome it is to select a column of keys on a staggered layout.

Interesting groups would be something like "keys down the left side", "the bottom row except space" and stuff like "every odd function key".

**Comment by ijprest** [comment] 2018-09-16 22:05
Duplicate of #6.

**Closed by ijprest** 2018-09-16 22:05 UTC
