### ISSUE TITLE
I'd like to be able to use one of my own layouts as a template

### ISSUE THREAD

**Issue by SarreqTeryx** [ijprest/keyboard-layout-editor#193] opened 2017-02-25 04:55 UTC
basically, I'd like to be able to copy my layouts.

**Comment by iandoug** [comment] 2017-03-28 15:31
Export it as .json and then import it again (import button bottom right on Raw Data tab)

**Comment by SarreqTeryx** [comment] 2017-03-29 06:45
i did realize that after submitting this, BUT, a way to do it from within the site, rather than cut and paste would still be infinitely better.

**Comment by iandoug** [comment] 2017-05-01 18:54
Sorry for late reply, but it's not cut-and-paste, but "save" and "upload" ... unless that's what you mean.

Alternatively clone the repo, run it locally, and add your layout to the menu.

Or you can simply log into github, then "Save" the layout, and add a bookmark to that.... :-)

**Comment by BartlomiejSkwira** [comment] 2018-07-09 15:48
The import feature is really hidden, I missed it (search quite a while) and had to google for a solution. Fortunately found this issue. I think it would be nice to have another "Upload JSON" button somewhere next to "Download/Save" buttons in the upper right corner.

**Comment by ijprest** [comment] 2018-09-14 06:39
Duplicate of #173.

**Closed by ijprest** 2018-09-14 06:39 UTC
Labels: duplicate

**Comment by ijprest** [comment] 2018-09-14 06:42
And #108.
