### ISSUE TITLE
New gist "Save" button overwrites previous layouts

### ISSUE THREAD

**Issue by skullydazed** [ijprest/keyboard-layout-editor#106] opened 2015-08-04 16:31 UTC
Under the old version of the save button when you clicked Save you got a new hash, and this made it easy to save several variations of a layout. With the new save button you always get the same hash. To save under a new hash I have to open a new tab and paste raw data over, and I have to remember to do this before I save any changes I've made.

This occurs even if you change the name of the keyboard, which I would expect to save under a new hash.

**Comment by ijprest** [comment] 2015-08-04 17:28
Saving to the same Gist is by design, but I can see the confusion.

Note that Github maintains a history of all your work, so you don't risk losing any data... though I admit it's a bit difficult at present to get at it.  (You currently have to go to 'My Layouts' on the dropdown, then 'View on GitHub', and from GitHub you can view all of your revisions.)

I'm going to close this as wont-fix, but I've logged enhancements #107, #108 and #109 to cover various aspects of this so they don't get lost.  Implementing those three things will go a long way to eliminating the confusion, I think.

Thanks!

**Closed by ijprest** 2015-08-04 17:28 UTC

**Comment by skullydazed** [comment] 2015-08-04 17:45
Thanks! I'll watch those enhancements for updates.
