### ISSUE TITLE
SVG output doesn't output legends

### ISSUE THREAD

**Issue by SarreqTeryx** [ijprest/keyboard-layout-editor#194] opened 2017-02-25 09:47 UTC
Key labels/legends are missing from the SVG output

**Comment by kamathln** [comment] 2017-03-08 12:29
Bump. I came here to report the same.

**Comment by bpartridge** [comment] 2017-03-16 22:29
Looking into the SVG output, it is missing the legend text entirely.

To reproduce: http://www.keyboard-layout-editor.com/#/gists/76e3488b18b70608258fc8a83e5ff313 yields the SVG file here: https://gist.github.com/bpartridge/4253c87d3d55441fbe7fb6ccb206ca34

SVG export will not include the text "dual-pane" or any other legend text; it's just the `rect`s for the cells themselves. And it also doesn't include custom CSS.

This wouldn't be as huge an issue if the exported raster images (png, jpg) were higher-resolution; as is, there's no good way to get usable output from the tool besides taking a screenshot.

**Comment by kamathln** [comment] 2017-03-18 12:48
>This wouldn't be as huge an issue if the exported raster images (png, jpg) were higher-resolution; 

I do not agree. I import the SVG into Inkscape, add other stuff that I am planning ( A mini LCD Display, An extra USB port, etc. ) . I also add other rectangles and use gradients to mimic a more 3d look. All that would be difficult if it was a high res png or jpeg. It would also lose explicit dimensional information.

**Comment by MarMun** [comment] 2017-11-23 14:56
> Key labels/legends are missing from the SVG output

Yep. Came to report this as well...

**Comment by SajeOne** [comment] 2018-01-08 03:56
Well that was a huge waste of time now that I found this out. :)

**Comment by iandoug** [comment] 2018-08-22 20:33
> This wouldn't be as huge an issue if the exported raster images (png, jpg) were higher-resolution; as is, there's no good way to get usable output from the tool besides taking a screenshot.


Those exports basically turn the "canvas" into an image. They can't increase the existing resolution.

I trust the people playing around with the SVG files are aware of Swill's tool that may be more useful?
That CAD output will be better for editing.
http://builder.swillkb.com/

**Comment by Mange** [comment] 2018-08-23 05:55
Here is my usecase, which I'm currently scripting using Selenium to drive a browser to go to KLE and download an image (really hacky, I know)

https://github.com/Mange/dotfiles/blob/72b59da395c8ede4104957d2182f9ac139f05f99/keyboard/README.md

Having an SVG image would allow me to render it more nicely at any resolution instead of downloading a huge PNG and hope the scaling doesn't make the font unreadable.

**Comment by ijprest** [comment] 2018-09-14 06:30
Duplicate of #148.

**Closed by ijprest** 2018-09-14 06:30 UTC
Labels: duplicate
