### ISSUE TITLE
documentation of layout code syntax

### ISSUE THREAD

**Issue by michaelrw10** [ijprest/keyboard-layout-editor#191] opened 2017-02-22 03:28 UTC
Sorry if there is a better way of asking about this, but I couldn't find a way of sending a private message, and I was unable to find anything about this in the readme.md or in the various folders/files. 

While using the GUI to make a layout is very handy and frequently used, I often like to look at and play around with the 'raw data' code (which i thin is json). I'm trying to figure out what all of the different keys/functions/etc mean and do, and what their syntax is, but many of them are still a mystery to me. For example:
```
		"x": 1.25
		"t": "#000000\n\n\n\n\n\n#10c200"
		"a": 4
		"f": 3
		"f2": 3
		"fa": [0,2,0,0,0,0,2]
		"w": 2.25
```
**this is what I know/think thus far**: 

- 'x'  -  inserts a gap of `<float>` length
- 't'  -  specifies color, and has a very specific syntax when dealing with keys with multiple legends (top/bot/mid), and the number of \n line breaks seems to also be important and/or designate horizontal justification
- 'a'  -  unknown
- 'f'  -  font size (but i think it may only apply to certain row(s))
- 'f2'  -  font size (maybe just for middle/bottom legends, but unsure)
- 'fa'  -  not really sure what this does or its syntax. it appears to move the legends around in various ways, but no idea how it works. sometimes I see a set/list of integers assigned, other times only a single int
- 'w'  -  appears to change the width of the keycap. not persistent, must be issued per key if non-default width is needed

Also, I'm not a programmer of any kind; all of my code writing experience is purely recreational/hobby. Just throwing that out there :)

Any info to help me with this, or even point me in the right direction would be greatly appreciated. Cheers

**Comment by ijprest** [comment] 2017-02-22 07:57
You've done a pretty good job figuring it out from usage alone.  :)

It's not entirely up-to-date, but the format is partially documented here:  https://github.com/ijprest/keyboard-layout-editor/wiki/Serialized-Data-Format

The 'fa' property is one of the newer additions that isn't documented properly.  Originally there was only 'f' and 'f2' (for primary / secondary font-sizes); now that each label can have its own size 'fa' is used (stands for Font-size Array).  The 'f' property is still the default for anything left out of the array.

It's been a while since I looked at it, but I think the order of the text colors (and 'fa' array) is the same as the order of the text labels themselves (which *is* documented).  The first color is probably the default for anything that is left blank.

**Comment by michaelrw10** [comment] 2017-02-23 02:29
thanks! Ive also figured out that the number of linebreaks that are used corresponds to the legend positioning. Like: 

```
{
		"t": "#000000\n\n\n\n\n\n\n\n\n#ff0000\n#ff0000",
		"w": 1.25
	},
	"Alt\n\n\n\n\n\n\n\n\ncustomline1 +\ncustomline2",
```
will result in centered legends.
Also, when you use the 'fa' property:
`{"fa": [0,0,0,0,0,0,0,0,0,0,0]} ` appears that each number corresponds to font size of a different location of the key. 0=default font size
the 11 font sizes in the list, in this order: TopLft,BotLft,TopRt,BotRt,-,-,MidLft,MidRt,TopMid,MidMid,BotMid

Cant seem to figure out what the 5 and 6 positions designate.. maybe deprecated?
anyways, thx for the reply! and thx for the tool. In case you're curious, I use it to map out a keyboard full of custom key binds for playing counter strike GO.

**Comment by ijprest** [comment] 2018-09-16 19:54
Duplicate of #21.

**Closed by ijprest** 2018-09-16 19:54 UTC
